# NumPy for AI/ML – Conceptual & Technical Assessment

## Module 3

**Name:** Tarani Marri

# NumPy Setup

NumPy is a Python library used for numerical computing. It provides arrays and functions that make it easier to perform mathematical and numerical operations efficiently.

Before using NumPy, it needs to be installed in the Python environment if it is not already available. In a Jupyter Notebook, NumPy can be installed using `%pip install numpy`.

In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### Explanation

The `import numpy as np` statement imports the NumPy library into the program. The alias `np` is used as a short name for NumPy, making it easier to access NumPy functions and operations.

In [8]:
# Import NumPy library
import numpy as np

# Section A – Conceptual Understanding

### Questions A1–A10

## A1. NumPy Arrays vs Python Lists
## Explanation
NumPy arrays are preferred for numerical work because they are more efficient for handling large amounts of numerical data. They usually use memory more efficiently than Python lists and allow mathematical operations to be performed on the whole array at once. NumPy also provides many built-in functions for calculations such as mean, sum, standard deviation, and matrix operations. Because of these features, NumPy is commonly used for data processing and numerical operations in AI and ML.

In [9]:
import numpy as np

# Create a normal Python list
numbers_list = [10, 20, 30, 40, 50]

# Create the same data as a NumPy array
numbers_array = np.array([10, 20, 30, 40, 50])

# Multiplying a Python list by 2 repeats the list
list_result = numbers_list * 2

# Multiplying a NumPy array by 2 multiplies each element
array_result = numbers_array * 2

print("Python list result:", list_result)
print("NumPy array result:", array_result)

Python list result: [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
NumPy array result: [ 20  40  60  80 100]


## A2. Vectorization and Its Importance in Large Datasets
## Explanation

Vectorization means performing an operation on an entire NumPy array at once instead of using a Python loop. It makes calculations faster because NumPy uses optimized operations to process the data. This is especially useful for large datasets where many values need to be processed. It also makes the code shorter and easier to understand.


In [10]:
import numpy as np

# Create an array of numbers
numbers = np.array([10, 20, 30, 40, 50])

# Perform multiplication on all elements at once
result = numbers * 2

# Display the result
print("Original array:", numbers)
print("Vectorized result:", result)

Original array: [10 20 30 40 50]
Vectorized result: [ 20  40  60  80 100]


## A3. Element-wise Multiplication and Matrix Multiplication
## Explanation

`A * B` performs element-wise multiplication, where each value in A is multiplied by the corresponding value in B. `A @ B` performs matrix multiplication, where rows of A are multiplied with columns of B. In a neural network, element-wise multiplication can be used for applying a mask or scaling values. Matrix multiplication is commonly used to calculate the weighted inputs of a neural-network layer.


In [11]:
import numpy as np

# Create two compatible 2D arrays
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Perform element-wise multiplication
element_wise = A * B

# Perform matrix multiplication
matrix_product = A @ B

print("A * B:")
print(element_wise)

print("A @ B:")
print(matrix_product)

A * B:
[[ 5 12]
 [21 32]]
A @ B:
[[19 22]
 [43 50]]


## A4. Broadcasting in NumPy
## Explanation

Broadcasting allows NumPy to perform element-wise operations on arrays with different but compatible shapes. NumPy compares the dimensions of the arrays starting from the rightmost side. The dimensions are compatible when they are equal or when one of them is 1. If the dimensions do not follow these rules, NumPy gives a shape-related error.


In [12]:
import numpy as np

# Create a 2D array
numbers = np.array([[1, 2, 3],
                    [4, 5, 6]])

# Create a single value
value = 10

# NumPy broadcasts 10 to every element of the array
result = numbers + value

print("Original array:")
print(numbers)

print("After broadcasting:")
print(result)

Original array:
[[1 2 3]
 [4 5 6]]
After broadcasting:
[[11 12 13]
 [14 15 16]]


## A5. flatten() vs ravel()
## Explanation
`flatten()` converts an array into a one-dimensional array and always creates a copy of the data. `ravel()` also converts an array into one dimension, but it can return a view of the original array when possible. Since a view does not need to create another full copy, it can save memory. For a memory-constrained application working with large images, I would prefer `ravel()` because it can use less additional memory.


In [13]:
import numpy as np

# Create a 2D array
image = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Flatten creates a copy
flat_array = image.flatten()

# Ravel returns a flattened view when possible
ravel_array = image.ravel()

print("Original array:")
print(image)

print("Using flatten():")
print(flat_array)

print("Using ravel():")
print(ravel_array)

Original array:
[[1 2 3]
 [4 5 6]]
Using flatten():
[1 2 3 4 5 6]
Using ravel():
[1 2 3 4 5 6]


## A6. Understanding Axis 0 and Axis 1
## Explanation

In a 2D NumPy array, `axis=0` performs the operation down the rows, giving a result for each column. `axis=1` performs the operation across the columns, giving a result for each row. For example, `np.sum()` with `axis=0` calculates the sum of each column, while `axis=1` calculates the sum of each row.


In [14]:
import numpy as np

# Create a 2D array
numbers = np.array([[1, 2, 3],
                    [4, 5, 6]])

# Sum of each column
column_sum = np.sum(numbers, axis=0)

# Sum of each row
row_sum = np.sum(numbers, axis=1)

print("Original array:")
print(numbers)

print("Sum along axis=0 (columns):")
print(column_sum)

print("Sum along axis=1 (rows):")
print(row_sum)

Original array:
[[1 2 3]
 [4 5 6]]
Sum along axis=0 (columns):
[5 7 9]
Sum along axis=1 (rows):
[ 6 15]


## A7. Normalization and Standardization
## Explanation

Normalization or standardization is important because different features may have different ranges or scales. If one feature has much larger values than another, it can affect the model's learning process. Normalization usually scales values to a fixed range such as 0 to 1. Standardization changes the data so that it has a mean of 0 and a standard deviation of 1.


In [15]:
import numpy as np

# Create sample feature values
data = np.array([10, 20, 30, 40, 50])

# Min-Max normalization to the range 0 to 1
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))

# Standardization using mean and standard deviation
standardized = (data - np.mean(data)) / np.std(data)

print("Original data:", data)
print("Normalized data:", normalized)
print("Standardized data:", standardized)

Original data: [10 20 30 40 50]
Normalized data: [0.   0.25 0.5  0.75 1.  ]
Standardized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


## A8. Handling NaN Values
## Explanation

`np.nanmean()` is used to calculate the mean while ignoring `NaN` (Not a Number) values in the data. This is useful when a dataset has missing values and we still want to calculate the average of the available values. If `np.mean()` is used directly on data containing a `NaN`, the result will usually be `NaN`. Therefore, `np.nanmean()` is useful for handling missing numerical data.


In [16]:
import numpy as np

# Create an array containing a NaN value
data = np.array([10, 20, np.nan, 40, 50])

# Calculate mean using np.mean()
mean_result = np.mean(data)

# Calculate mean while ignoring NaN using np.nanmean()
nanmean_result = np.nanmean(data)

print("Using np.mean():", mean_result)
print("Using np.nanmean():", nanmean_result)

Using np.mean(): nan
Using np.nanmean(): 30.0


## A9. Shape of RGB Image Batches
## Explanation

For normal ML data, `X.shape = (samples, features)` means that each row represents one sample and each column represents a feature. For RGB images, we need extra dimensions for the image height, width, and color channels. A batch of RGB images is usually represented as `(samples, height, width, channels)`. Therefore, 64 RGB images of size 128 × 128 have the shape **`(64, 128, 128, 3)`**, where `3` represents the RGB channels.


In [17]:
import numpy as np

# Create a batch of 64 RGB images
images = np.zeros((64, 128, 128, 3))

# Display the shape of the image batch
print("Shape of RGB image batch:", images.shape)

Shape of RGB image batch: (64, 128, 128, 3)


## A10. Reproducibility and Random Seeds
## Explanation

Reproducibility means getting the same results when an experiment is run again under the same conditions. It is important in ML because random values are often used when creating data, initializing models, or testing algorithms. Using `np.random.default_rng(seed)` with a fixed seed makes the generated random values repeatable. This helps us compare experiments and find errors more easily.


In [18]:
import numpy as np

# Create a random number generator with a fixed seed
rng1 = np.random.default_rng(42)

# Generate some random values
values1 = rng1.random(5)

# Create another generator with the same seed
rng2 = np.random.default_rng(42)

# Generate random values again
values2 = rng2.random(5)

print("First run:", values1)
print("Second run:", values2)

# Check whether both results are identical
print("Same results:", np.array_equal(values1, values2))

First run: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Second run: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Same results: True


# Section B – Predict the Output
### Questions B1–B8


## B1. Broadcasting Shape
## Explanation

The array a has shape (3,) and b has shape (3, 1).
NumPy uses broadcasting to make their shapes compatible for addition.
The result contains 3 rows and 3 columns.
Therefore, the resulting shape is (3, 3).
## predicted output
Output:
(3, 3)


In [20]:
import numpy as np

# Create a 1D array
a = np.array([1, 2, 3])

# Create a 2D column array
b = np.array([[1], [2], [3]])

# Add the arrays using broadcasting
result = a + b

# Print the shape of the result
print(result.shape)

(3, 3)


## B2. Array Slicing
## Explanation

np.arange(1, 7) creates the numbers from 1 to 6.
After reshaping, the array becomes [[1, 2, 3], [4, 5, 6]].
x[:, 1] selects the second column from both rows.
Therefore, the output is [2 5].
## predicted output
Output:
[2 5]

In [21]:
import numpy as np

# Create numbers from 1 to 6 and reshape them into 2 rows and 3 columns
x = np.arange(1, 7).reshape(2, 3)

# Select all rows and the second column
result = x[:, 1]

# Print the selected values
print(result)

[2 5]


## B3. Boolean Indexing
## Explanation

The expression arr % 10 == 0 checks which values are divisible by 10.
The condition is true for 10 and 20.
NumPy uses this condition to select only those values from the array.
Therefore, the output is [10 20].
## predicted output
output:
[10,20]



In [22]:
import numpy as np

# Create an array of numbers
arr = np.array([5, 10, 15, 20, 25])

# Select values that are exactly divisible by 10
result = arr[arr % 10 == 0]

# Print the selected values
print(result)

[10 20]


## B4. Matrix Multiplication
## Explanation
The transpose of `m` changes the rows into columns.
The `@` operator performs matrix multiplication between `m.T` and `m`.
Each element is calculated by multiplying corresponding values and adding them.
Therefore, the final matrix is **`[[10, 14], [14, 20]]`**.
## predicted output
output:
[[10 14]
 [14 20]]


In [23]:
import numpy as np

# Create a 2D matrix
m = np.array([[1, 2],
              [3, 4]])

# Transpose the matrix and perform matrix multiplication
result = m.T @ m

# Print the result
print(result)

[[10 14]
 [14 20]]


## B5. Handling NaN Values
## Explanation

np.mean() returns nan because the array contains a NaN value.
np.nanmean() ignores the NaN and calculates the mean of the remaining values.
The remaining values are 1, 2, 4, whose mean is 2.3333333333333335.
Therefore, the output is nan 2.3333333333333335.

## predicted output
output:
nan 2.3333333333333335



In [24]:
import numpy as np

# Create an array containing a NaN value
data = np.array([1, 2, np.nan, 4])

# Calculate the normal mean and mean ignoring NaN
mean_result = np.mean(data)
nanmean_result = np.nanmean(data)

# Print both results
print(mean_result, nanmean_result)

nan 2.3333333333333335


## B6. `np.where()` Conditional Selection
## Explanation

The condition checks whether each value is greater than `15`.
`10` is not greater than `15`, so it gets `0`.
`20` and `30` are greater than `15`, so they get `1`.
Therefore, the output is **`[0 1 1]`**.
## predicted output
output:
[0 1 1]

In [25]:
import numpy as np

# Create an array of values
x = np.array([10, 20, 30])

# Assign 1 if the value is greater than 15, otherwise assign 0
y = np.where(x > 15, 1, 0)

# Print the result
print(y)

[0 1 1]


## B7. Array Dimensions and Size
## Explanation

The array has 3 rows and 4 columns, so it is a 2-dimensional array.
Therefore, `a.ndim` returns `2`.
The total number of elements is `3 × 4 = 12`.
Therefore, `a.size` returns **`12`**.
## predicted output
output:
2 12


In [26]:
import numpy as np

# Create an array with 3 rows and 4 columns
a = np.zeros((3, 4))

# Print the number of dimensions and total number of elements
print(a.ndim, a.size)

2 12


## B8. Array Reversal and Slicing
## Explanation:
The original array contains numbers from 1 to 12 arranged in 3 rows and 4 columns.
`[::-1]` reverses the order of the rows and columns.
So, the last row becomes the first row and each row is also reversed.
Therefore, the output starts with **`[12 11 10 9]`** and ends with **`[4 3 2 1]`**.
## predicted output
output:
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [27]:
import numpy as np

# Create numbers from 1 to 12 and reshape them into 3 rows and 4 columns
arr = np.arange(1, 13).reshape(3, 4)

# Reverse the rows and columns
result = arr[::-1, ::-1]

# Print the reversed array
print(result)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


# Section C – Coding / Implementation
### Questions C1–C8


## C1. Pass or Fail Labels
## Explanation
`np.where()` checks the condition for every score in the array.
If the score is 40 or more, it assigns the label `P`.
If the score is below 40, it assigns the label `F`.
This performs the labeling without using a Python loop.


In [28]:
import numpy as np

# Create an array of exam scores
scores = np.array([35, 42, 67, 28, 90, 55])

# Assign P for scores >= 40 and F for scores < 40
labels = np.where(scores >= 40, 'P', 'F')

# Display the scores and their labels
print("Scores:", scores)
print("Labels:", labels)

Scores: [35 42 67 28 90 55]
Labels: ['F' 'P' 'P' 'F' 'P' 'P']


## C2. Z-Score Standardization
## Explanation
The function first calculates the mean and standard deviation using NumPy.
Each value is then converted into its z-score using `(x - mean) / std`.
The standardized values have a mean close to 0 and a standard deviation close to 1.
This makes the values easier to compare on the same scale.


In [29]:
import numpy as np

# Define a function to standardize an array
def standardize(x):
    # Calculate the mean and standard deviation
    mean = np.mean(x)
    std = np.std(x)

    # Return the z-score standardized values
    return (x - mean) / std

# Create a sample array
data = np.array([10, 20, 30, 40, 50])

# Standardize the data
result = standardize(data)

# Display the result
print("Original data:", data)
print("Standardized data:", result)

Original data: [10 20 30 40 50]
Standardized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


## C3. Combining Batches
## Explanation
Both batches have the same number of features, which is 3.
`np.vstack()` combines them vertically by adding the rows of the second batch below the first.
The first batch has 2 rows and the second has 3 rows.
Therefore, the combined array has the shape **`(5, 3)`**.


In [30]:
import numpy as np

# Create the first batch with 2 samples and 3 features
batch1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Create the second batch with 3 samples and 3 features
batch2 = np.array([[7, 8, 9],
                   [10, 11, 12],
                   [13, 14, 15]])

# Combine the batches along the rows
combined = np.vstack((batch1, batch2))

# Print the combined array and its shape
print("Combined array:")
print(combined)
print("Shape:", combined.shape)

Combined array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Shape: (5, 3)


## C4. Vectorized Matrix Standardization
## Explanation
`axis=0` calculates the mean and standard deviation separately for each feature column.
The expression `(X - mean) / std` standardizes all 100 rows at once using broadcasting.
No explicit Python loop is required for the calculation.
The shape remains **`(100, 5)`** because standardization does not change the matrix dimensions.


In [31]:
import numpy as np

# Create a matrix with 100 samples and 5 features
X = np.random.default_rng(42).random((100, 5))

# Calculate the mean and standard deviation of each column
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

# Standardize the complete matrix using broadcasting
X_standardized = (X - mean) / std

# Print the shape of the standardized matrix
print("Shape:", X_standardized.shape)

Shape: (100, 5)


## C5. Linear Model Prediction and MSE
## Explanation
The expression `X @ w + b` calculates the predicted values using matrix multiplication.
The predictions are compared with the actual values stored in `y_true`.
MSE calculates the average of the squared differences between actual and predicted values.
A smaller MSE means the predictions are closer to the actual values.


In [32]:
import numpy as np

# Create input data with 3 samples and 2 features
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

# Create the weight vector
w = np.array([0.5, 1.0])

# Set the bias value
b = 2.0

# Create the actual target values
y_true = np.array([5, 7, 9])

# Calculate predictions using y_pred = X @ w + b
y_pred = X @ w + b

# Calculate Mean Squared Error
mse = np.mean((y_true - y_pred) ** 2)

print("Predictions:", y_pred)
print("MSE:", mse)

Predictions: [4.5 6.  7.5]
MSE: 1.1666666666666667


## C6. Reproducible Random Data
## Explanation
`normal()` generates random values from a normal distribution.
The shape `(10, 3)` means there are 10 samples and 3 features.
Both generators use the same seed, so they produce the same random values.
This makes the experiment reproducible.


In [33]:
import numpy as np

# Create a random number generator with a fixed seed
rng1 = np.random.default_rng(42)

# Generate 10 samples with 3 features
data1 = rng1.normal(size=(10, 3))

# Create another generator using the same seed
rng2 = np.random.default_rng(42)

# Generate the same data again
data2 = rng2.normal(size=(10, 3))

# Print the shape and check whether both arrays are identical
print("Shape:", data1.shape)
print("Same values:", np.array_equal(data1, data2))

Shape: (10, 3)
Same values: True


## C7. Min-Max Normalization
## Explanation
The minimum pixel value is mapped to `0` and the maximum value is mapped to `1`.
All other pixel values are scaled between these two values.
The calculation uses the minimum and maximum values of the image.
This converts the original pixel range from `0–255` to `0–1`.


In [34]:
import numpy as np

# Create a small grayscale image with pixel values from 0 to 255
image = np.array([[0, 128],
                  [200, 255]])

# Normalize the pixel values to the range 0 to 1
normalized = (image - np.min(image)) / (np.max(image) - np.min(image))

# Display the original and normalized images
print("Original image:")
print(image)

print("Normalized image:")
print(normalized)

Original image:
[[  0 128]
 [200 255]]
Normalized image:
[[0.         0.50196078]
 [0.78431373 1.        ]]


## C8. Average Pixel Value of RGB Images
## Explanation
The image batch has the shape `(4, 28, 28, 3)`, representing 4 RGB images.
`axis=(1, 2, 3)` averages across the height, width, and RGB channels.
This leaves only the first dimension, which represents the 4 images.
Therefore, the result contains one average pixel value for each image.


In [35]:
import numpy as np

# Create a batch of 4 RGB images of size 28 x 28
rng = np.random.default_rng(42)
images = rng.random((4, 28, 28, 3))

# Calculate the average pixel value for each image
average_values = np.mean(images, axis=(1, 2, 3))

# Display the shape and average value of each image
print("Image batch shape:", images.shape)
print("Average value of each image:")
print(average_values)

Image batch shape: (4, 28, 28, 3)
Average value of each image:
[0.49879444 0.49546077 0.48993754 0.50644914]


# Section D – Applied / Scenario-Based Problems
### Questions D1-D3



## D1. Data Preprocessing Pipeline

### Step 1: Detect Missing Values

We can use `np.isnan()` to identify the `NaN` values in the array.
`np.any(np.isnan(data))` checks whether the array contains at least one missing value.
This helps us identify missing data before processing it.

### Step 2: Handle Missing Values

For this example, I will replace the missing values with the mean of their respective columns.
Mean imputation is useful when only a small number of values are missing and the remaining values are available.
After replacing the `NaN` values, the data can be used for further processing.

### Step 3: Standardize the Data

After handling the missing values, we calculate the mean and standard deviation of each column.
Using `(data - mean) / std`, each feature is standardized separately.
This gives the features a mean close to 0 and a standard deviation close to 1.

## Explanation 
The pipeline detects missing values, replaces them using column means, and then standardizes each feature so the cleaned data is ready for a machine-learning model.


In [36]:
import numpy as np

# Create a sample 2D array containing a NaN value
data = np.array([[10, 20],
                 [15, np.nan],
                 [20, 40],
                 [25, 50]], dtype=float)

# Step 1: Detect missing values
missing_values = np.isnan(data)

print("Missing value locations:")
print(missing_values)

print("Contains NaN:", np.any(missing_values))

# Step 2: Replace NaN values with the column mean
column_means = np.nanmean(data, axis=0)

# Find the positions of NaN values
rows, columns = np.where(np.isnan(data))

# Replace each NaN with the mean of its column
data[rows, columns] = column_means[columns]

print("\nData after handling NaN:")
print(data)

# Step 3: Standardize the clean data
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)

standardized_data = (data - mean) / std

print("\nStandardized data:")
print(standardized_data)

Missing value locations:
[[False False]
 [False  True]
 [False False]
 [False False]]
Contains NaN: True

Data after handling NaN:
[[10.         20.        ]
 [15.         36.66666667]
 [20.         40.        ]
 [25.         50.        ]]

Standardized data:
[[-1.34164079 -1.5430335 ]
 [-0.4472136   0.        ]
 [ 0.4472136   0.3086067 ]
 [ 1.34164079  1.2344268 ]]


## D2. Image Batch Understanding

### 1. Single RGB Image vs Batch

A single RGB image is represented using the shape **`(height, width, channels)`**.
For a 64 × 64 RGB image, the shape is **`(64, 64, 3)`**, where `3` represents the RGB channels.
A batch of 16 such images adds one extra dimension for the number of images.
Therefore, the batch shape is **`(16, 64, 64, 3)`**.

### 2. Create a Dummy Image Batch

We can use `np.random.default_rng()` to generate random pixel values.
Here, the pixel values are generated between 0 and 255.
The resulting array represents 16 RGB images of size 64 × 64.

### 3. Calculate the Average Image

To calculate the average image, we take the mean across the first axis using `axis=0`.
This calculates the average value of each pixel position across all 16 images.
The height, width, and RGB channel dimensions remain unchanged.

### 4. Result Shape and Explanation

The average image has the shape **`(64, 64, 3)`**.
When `axis=0` is used, NumPy averages the 16 images together.
The batch dimension `16` is removed, while height, width, and RGB channels remain.
Therefore, the result is one average RGB image of size 64 × 64.


In [1]:
import numpy as np

# Create a random number generator
rng = np.random.default_rng(42)

# Create a batch of 16 RGB images
# Shape: (number of images, height, width, RGB channels)
images = rng.integers(0, 256, size=(16, 64, 64, 3))

# Calculate the average image across the 16 images
average_image = np.mean(images, axis=0)

# Print the shapes
print("Single RGB image shape:", images[0].shape)
print("Batch shape:", images.shape)
print("Average image shape:", average_image.shape)

Single RGB image shape: (64, 64, 3)
Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


## D3. Debugging Model Code

### Bug 1: Incorrect Weight Shape

`X` has the shape **`(3, 2)`**, meaning there are 3 samples and 2 features.
Therefore, the weight vector must contain 2 values and have shape **`(2,)`**.
The given `w` has 3 values, so `X @ w` cannot perform matrix multiplication.
The corrected weight vector is `w = np.array([0.5, 1.0])`.

### Bug 2: Incorrect MSE Calculation

The expression `y_true - y_pred ** 2` is incorrect because exponentiation (`**`) is performed before subtraction.
It calculates `y_true - (y_pred ** 2)` instead of squaring the prediction error.
The correct expression is **`np.mean((y_true - y_pred) ** 2)`**.
The parentheses ensure that the difference is calculated before squaring.

**Final explanation:** There are two bugs: the weight vector has the wrong shape, and the MSE expression has incorrect parentheses. After changing `w` to shape `(2,)` and using `np.mean((y_true - y_pred) ** 2)`, the model code works correctly.


In [2]:
import numpy as np

# X has 3 samples and 2 features
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

# Weight vector must have 2 values because X has 2 features
w = np.array([0.5, 1.0])

# Set the bias
b = 2.0

# Actual target values
y_true = np.array([10, 20, 30])

# Calculate predicted values
y_pred = X @ w + b

# Calculate Mean Squared Error correctly
mse = np.mean((y_true - y_pred) ** 2)

# Display the results
print("y_pred:", y_pred)
print("MSE:", mse)

y_pred: [4.5 6.  7.5]
MSE: 244.16666666666666


# Section E – Bonus / Challenge
### Questions E1 and E2

## E1. Per-Column Min-Max Normalization

Min-max normalization can be applied separately to each feature column.
Using `axis=0`, NumPy calculates the minimum and maximum value of each column.
The formula `(X - min) / (max - min)` scales every column independently to the range 0 to 1.
This is fully vectorized and does not require any explicit Python loops

## Explanation
Each feature column is normalized independently, so the minimum becomes `0` and the maximum becomes `1` in every column.


In [4]:
import numpy as np

# Create a 2D feature matrix
X = np.array([[10, 100, 1000],
              [20, 200, 2000],
              [30, 300, 3000],
              [40, 400, 4000]], dtype=float)

# Find the minimum value of each column
col_min = np.min(X, axis=0)

# Find the maximum value of each column
col_max = np.max(X, axis=0)

# Apply min-max normalization column-wise
X_normalized = (X - col_min) / (col_max - col_min)

# Display the results
print("Original matrix:")
print(X)

print("\nColumn minimums:")
print(col_min)

print("\nColumn maximums:")
print(col_max)

print("\nNormalized matrix:")
print(X_normalized)

Original matrix:
[[  10.  100. 1000.]
 [  20.  200. 2000.]
 [  30.  300. 3000.]
 [  40.  400. 4000.]]

Column minimums:
[  10.  100. 1000.]

Column maximums:
[  40.  400. 4000.]

Normalized matrix:
[[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]


## E2. Three-Level Score Classification

The scores can be classified using nested `np.where()` without using `if/else` statements or loops.
Scores below 40 are labeled **Fail**.
Scores from 40 to 70 are labeled **Average**, and scores above 70 are labeled **Excellent**.
The entire classification is performed as one vectorized expression.
## Explanation
 The first `np.where()` checks whether a score is below 40.
If it is not, the second `np.where()` checks whether it is 70 or below.
This correctly assigns `Fail`, `Average`, or `Excellent` to every score.
No explicit loop or `if/else` statement is used.


In [5]:
import numpy as np

# Create an array of exam scores
scores = np.array([25, 40, 55, 70, 75, 90])

# Classify the scores using nested np.where()
result = np.where(scores < 40, "Fail",
                  np.where(scores <= 70, "Average", "Excellent"))

# Display the scores and classifications
print("Scores:", scores)
print("Classification:", result)

Scores: [25 40 55 70 75 90]
Classification: ['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']


# Thank You!
